export const CC_TEXTS = {
  kpi: {
    totalPoints: "Total Puntos",
    activeTelemetry: "Telemetría Activa",
    compliance: "Cumplimiento Normativo",
    warnings: "Warnings",
  },
  tabs: {
    telemetry: "Telemetría",
    compliance: "Cumplimiento",
  },
  module: {
    title: "Centro de Control",
  },
  errors: {
    loadControlCenter: "Error cargando el Centro de Control",
    retry: "Reintentar",
    loadMeasurements: "Error cargando mediciones",
    loadPoint: "Error cargando punto",
    loadFlow: "Error cargando datos de caudal",
    loadConfig: "Error cargando configuración",
    downloadImage: "Error al descargar imagen",
    loadCompliance: "Error cargando cumplimiento",
    createTicket: "Error al crear el ticket",
    navigateDate: "Error navegando fecha",
  },
  warnings: {
    title: "Warnings",
    total: "total",
    empty: "Sin warnings para este punto",
  },
  compliance: {
    withinLimits: "Dentro de límites",
    nearLimit: "Cerca de superar límite",
    breach: "Incumplimiento detectado",
    noLimits: "Sin límites configurados",
    safe: "Cumplimiento",
    warning: "Advertencia",
    critical: "Crítico",
  },
  voucher: {
    title: "Voucher DGA",
    validating: "Validando...",
    validate: "Validar",
    ready: "Listo para validar...",
    notFound: "Comprobante no encontrado",
    connectionError: "Error de conexión",
    consoleHint: "Revisa la consola para más detalles",
    notValidated: "Sin validar",
    validateHint: "para verificar",
    copyJson: "Copiar JSON",
    copied: "Respuesta copiada",
    fields: {
      flow: "Caudal",
      totalizer: "Totalizador",
      date: "Fecha",
      time: "Hora",
      point: "Punto",
      code: "Código",
      type: "Tipo",
      sent: "Enviado",
      yes: "Sí",
      no: "No",
    },
  },
  flow: {
    exceedances: "Excedencias de caudal",
    nearLimits: "Veces cerca del límite",
    noExceedances: "Sin excedencias registradas este año",
    noEvents: "Sin eventos cercanos al límite este año",
    columns: {
      dateTime: "Fecha/Hora",
      pctLimit: "% del límite",
      authorized: "Autorizado",
      flow: "Caudal",
    },
  },
  measurements: {
    period: "Período",
    loggerTime: "Fecha logger",
    time: "Hora",
    flow: "Caudal (L/s)",
    level: "Nivel (m)",
    waterTable: "Nivel freático (m)",
    total: "Total (m³)",
    consumption: "Consumo (m³)",
    status: "Estado",
    noData: "Sin mediciones para este día",
    noHydrometry: "Sin datos de hidrometría para este punto",
    noLevels: "Sin datos de niveles para este punto",
    noLevel: "Sin datos de nivel",
    noWaterTable: "Sin datos de nivel freático",
    noLevelsChart: "Sin datos de niveles",
    selectPoint: "Seleccionar punto",
    askMe: "Preguntame sobre tus puntos...",
    exportCsv: "Exportar CSV",
    exportPng: "Exportar PNG",
  },
  stop: {
    telemetry: "Solicitud para detener telemetría",
    compliance: "Solicitud para detener cumplimiento",
    requestedBy: "Solicitado por",
    startDate: "Fecha inicio",
    endDate: "Fecha fin",
    reason: "Razón de la solicitud",
    cancel: "Cancelar",
    submit: "Enviar solicitud",
    placeholder: "Ej: Mantenimiento programado del sensor...",
    placeholderCompliance: "Ej: Pausa temporal por reconfiguración normativa...",
    technicalReport: "Informe Técnico requerido",
    detailedReport: "Informe Detallado Obligatorio",
    technicalReportDesc: "La detención supera los 5 días. Se debe enviar el Informe Técnico (formato libre) que cumpla con los fundamentos principales y cuyo objetivo sea evidenciar las actividades realizadas en terreno.",
    detailedReportDesc: "La detención supera los 10 días. Se debe confeccionar un informe detallado de las actividades realizadas en terreno, evidenciando cada una de las labores ejecutadas.",
    start: "Inicio",
    end: "Fin",
  },
  support: {
    title: "Solicitud de soporte",
    description: "Descripción del problema",
    descriptionPlaceholder: "Describe el problema o solicitud...",
    priority: "Prioridad",
    priorityPlaceholder: "Selecciona la prioridad",
  },
  complianceDetail: {
    lastSent: "Último envío a DGA/SMA",
    date: "Fecha",
    voucher: "Voucher",
    flowSent: "Caudal enviado",
    totalSent: "Total enviado",
  },
  status: {
    error: "Error",
    confirmed: "Confirmado",
  },
  chat: {
    title: "Experto en Telemetria",
    subtitle: "Smart Hydro - Consultas en tiempo real",
    objective: "Objetivo:",
    objectiveDesc: "Ayudarte a interpretar tus datos de telemetria, consumo, caudal y cumplimiento normativo en tiempo real.",
    clear: "Limpiar chat",
    hello: "Hola! Soy tu asistente de telemetria. En que puedo ayudarte?",
    error: "Ups, hubo un error. Intenta de nuevo.",
    noAnswer: "No tengo una respuesta en este momento.",
    suggestions: [
      "Como va mi consumo?",
      "Que punto consumio mas hoy?",
    ],
    quotaUsed: "Preguntas usadas",
    quotaAvailable: "disponibles",
  },
  types: {
    DGA: "DGA",
    SMA: "SMA",
  },
  placeholders: {
    selectPoint: "Seleccionar punto",
  },
};
